[debug] [2024-06-21T08:06:04.154Z] ----------------------------------------------------------------------
[debug] [2024-06-21T08:06:04.155Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\merti\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2024-06-21T08:06:04.156Z] CLI Version:   13.11.2
[debug] [2024-06-21T08:06:04.156Z] Platform:      win32
[debug] [2024-06-21T08:06:04.156Z] Node Version:  v18.18.0
[debug] [2024-06-21T08:06:04.157Z] Time:          Fri Jun 21 2024 13:36:04 GMT+0530 (India Standard Time)
[debug] [2024-06-21T08:06:04.157Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-06-21T08:06:04.217Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2024-06-21T08:06:04.218Z] > authorizing via signed-in user (rathorejaimalbanna@gmail.com)
[debug] [2024-06-21T08:06:04.218Z] [iam] checking project brokerage-house for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2024-06-21T08:06:04.219Z] > refreshing access token with scopes: []
[debug] [2024-06-21T08:06:04.221Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2024-06-21T08:06:04.221Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2024-06-21T08:06:25.362Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------304364217604868182745722","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: connect ETIMEDOUT 2404:6800:4002:825::200a:443
[debug] [2024-06-21T08:06:25.363Z] [iam] error while checking permissions, command may fail: FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2024-06-21T08:06:25.363Z] > refreshing access token with scopes: []
[debug] [2024-06-21T08:06:25.364Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2024-06-21T08:06:25.364Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2024-06-21T08:06:46.418Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------262700850149251127487914","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: connect ETIMEDOUT 2404:6800:4002:825::200a:443
[debug] [2024-06-21T08:06:46.418Z] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2024-06-21T08:06:51.439Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\merti\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:267:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2024-06-21T08:07:32.659Z] ----------------------------------------------------------------------
[debug] [2024-06-21T08:07:32.661Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\merti\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2024-06-21T08:07:32.661Z] CLI Version:   13.11.2
[debug] [2024-06-21T08:07:32.662Z] Platform:      win32
[debug] [2024-06-21T08:07:32.662Z] Node Version:  v18.18.0
[debug] [2024-06-21T08:07:32.662Z] Time:          Fri Jun 21 2024 13:37:32 GMT+0530 (India Standard Time)
[debug] [2024-06-21T08:07:32.662Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-06-21T08:07:32.722Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2024-06-21T08:07:32.722Z] > authorizing via signed-in user (rathorejaimalbanna@gmail.com)
[debug] [2024-06-21T08:07:32.722Z] [iam] checking project brokerage-house for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2024-06-21T08:07:32.724Z] > refreshing access token with scopes: []
[debug] [2024-06-21T08:07:32.725Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2024-06-21T08:07:32.725Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2024-06-21T08:07:53.806Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------138111546628341032750367","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: connect ETIMEDOUT 2404:6800:4002:825::200a:443
[debug] [2024-06-21T08:07:53.807Z] [iam] error while checking permissions, command may fail: FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2024-06-21T08:07:53.807Z] > refreshing access token with scopes: []
[debug] [2024-06-21T08:07:53.808Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2024-06-21T08:07:53.808Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2024-06-21T08:08:14.852Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------373850974529483298848669","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: connect ETIMEDOUT 2404:6800:4002:825::200a:443
[debug] [2024-06-21T08:08:14.852Z] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2024-06-21T08:08:19.858Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\merti\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:267:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
