[debug] [2024-05-03T15:13:42.245Z] ----------------------------------------------------------------------
[debug] [2024-05-03T15:13:42.248Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\merti\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2024-05-03T15:13:42.249Z] CLI Version:   13.7.5
[debug] [2024-05-03T15:13:42.250Z] Platform:      win32
[debug] [2024-05-03T15:13:42.250Z] Node Version:  v18.18.0
[debug] [2024-05-03T15:13:42.255Z] Time:          Fri May 03 2024 20:43:42 GMT+0530 (India Standard Time)
[debug] [2024-05-03T15:13:42.255Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-05-03T15:13:42.261Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2024-05-03T15:13:42.456Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2024-05-03T15:13:42.457Z] > authorizing via signed-in user (rathorejaimalbanna@gmail.com)
[debug] [2024-05-03T15:13:42.457Z] [iam] checking project brokerage-house for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2024-05-03T15:13:42.460Z] > refreshing access token with scopes: []
[debug] [2024-05-03T15:13:42.463Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2024-05-03T15:13:42.463Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2024-05-03T15:14:03.511Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------508992309286906940394386","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: connect ETIMEDOUT 2404:6800:4002:81f::200a:443
[debug] [2024-05-03T15:14:03.513Z] [iam] error while checking permissions, command may fail: FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2024-05-03T15:14:03.514Z] > refreshing access token with scopes: []
[debug] [2024-05-03T15:14:03.516Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2024-05-03T15:14:03.517Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2024-05-03T15:14:03.551Z] *** [apiv2] error from fetch(https://firebase-public.firebaseio.com/cli.json, {"headers":{},"method":"GET"}): FetchError: request to https://firebase-public.firebaseio.com/cli.json failed, reason: connect ETIMEDOUT 2600:1901:0:4d00:::443
[warn] !  Unable to fetch the CLI MOTD and remote config. This is not a fatal error, but may indicate an issue with your network connection. 
[debug] [2024-05-03T15:14:03.553Z] Failed to fetch MOTD FirebaseError: Failed to make request to https://firebase-public.firebaseio.com/cli.json
[debug] [2024-05-03T15:14:24.562Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------552749113382614957688373","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: connect ETIMEDOUT 2404:6800:4002:81f::200a:443
[debug] [2024-05-03T15:14:24.563Z] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2024-05-03T15:14:29.582Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\merti\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:261:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2024-05-03T15:17:15.925Z] ----------------------------------------------------------------------
[debug] [2024-05-03T15:17:15.928Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\merti\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2024-05-03T15:17:15.929Z] CLI Version:   13.7.5
[debug] [2024-05-03T15:17:15.930Z] Platform:      win32
[debug] [2024-05-03T15:17:15.931Z] Node Version:  v18.18.0
[debug] [2024-05-03T15:17:15.933Z] Time:          Fri May 03 2024 20:47:15 GMT+0530 (India Standard Time)
[debug] [2024-05-03T15:17:15.933Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-05-03T15:17:15.939Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2024-05-03T15:17:16.137Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2024-05-03T15:17:16.137Z] > authorizing via signed-in user (rathorejaimalbanna@gmail.com)
[debug] [2024-05-03T15:17:16.138Z] [iam] checking project brokerage-house for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2024-05-03T15:17:16.139Z] > refreshing access token with scopes: []
[debug] [2024-05-03T15:17:16.141Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2024-05-03T15:17:16.141Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2024-05-03T15:17:37.192Z] *** [apiv2] error from fetch(https://firebase-public.firebaseio.com/cli.json, {"headers":{},"method":"GET"}): FetchError: request to https://firebase-public.firebaseio.com/cli.json failed, reason: connect ETIMEDOUT 2600:1901:0:4d00:::443
[warn] !  Unable to fetch the CLI MOTD and remote config. This is not a fatal error, but may indicate an issue with your network connection. 
[debug] [2024-05-03T15:17:37.195Z] Failed to fetch MOTD FirebaseError: Failed to make request to https://firebase-public.firebaseio.com/cli.json
[debug] [2024-05-03T15:17:37.345Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------653172676128265296392147","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: connect ETIMEDOUT 2404:6800:4002:811::200a:443
[debug] [2024-05-03T15:17:37.346Z] [iam] error while checking permissions, command may fail: FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2024-05-03T15:17:37.347Z] > refreshing access token with scopes: []
[debug] [2024-05-03T15:17:37.348Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2024-05-03T15:17:37.348Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2024-05-03T15:17:58.399Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------923348576430165537466264","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: connect ETIMEDOUT 2404:6800:4002:811::200a:443
[debug] [2024-05-03T15:17:58.400Z] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2024-05-03T15:18:03.419Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\merti\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:261:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
